[package]
name = "nrfutil-rs"
version = "0.1.0"
authors = ["Lotte Steenbrink <lotte.steenbrink@ferrous-systems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.0"
num-derive = "0.3"
num-traits = "0.2"
byteorder = "1.4.3"
